index:
  path: /
  defaults: { _controller:AppBundle:Main:index }

register:
  path: /register
  defaults: { _controller:AppBundle:Register:index }
  
home:
  path: /home
  defaults: { _controller:AppBundle:Home:index }

tournaments:
  path: /tournaments/{platform}
  defaults: { _controller:AppBundle:Tournaments:index }

game:
  path: /tournaments_game
  defaults: { _controller:AppBundle:Tournaments:game }

active_account:
  path: /active_account/{username}
  defaults: { _controller:AppBundle:Register:active_account }

group:
  path: /group
  defaults: { _controller:AppBundle:Group:index }

groups_json:
  path: /group/groups_json/{filter_group}/{id_platform}
  defaults: { _controller:AppBundle:Group:get_groups }

close_group:
  path: /group/close_group/{id_group}
  defaults: { _controller:AppBundle:Group:close_group }

register_group:
  path: /group/register_group/{id_group}/{id_user}
  defaults: { _controller:AppBundle:Group:register_group }

signdown_group:
  path: /group/signdown_group/{id_group}
  defaults: { _controller:AppBundle:Group:signdown_group }

chat:
  path: /group/chat/{id_group}
  defaults: { _controller:AppBundle:Group:chat_group }

get_messages:
  path: /group/chat/get_messages
  defaults: { _controller:AppBundle:Group:get_messages }

add_message:
  path: /group/chat/{id_group}/add_message
  defaults: { _controller:AppBundle:Group:add_message }

like_post:
  path: /home/likepost/{id_post}
  defaults: { _controller:AppBundle:Home:likePost }

unlike_post:
  path: /home/unlikepost/{id_post}
  defaults: { _controller:AppBundle:Home:unlikePost }

profile:
  path: /profile/{username}
  defaults: { _controller:AppBundle:Profile:index }

followers_user:
  path: /profile/followers/{username}
  defaults: { _controller:AppBundle:Profile:followers }

followings_user:
  path: /profile/followings/{username}
  defaults: { _controller:AppBundle:Profile:followings }

follow_user:
  path: /follow/{id_user}/{id_follower}
  defaults: { _controller:AppBundle:Follow:follow }

unfollow_user:
  path: /unfollow/{id_user}/{id_follower}
  defaults: { _controller:AppBundle:Follow:unfollow }

likes_user:
  path: /profle/likes/{username}
  defaults: { _controller:AppBundle:Profile:likes }

my_data_profile:
  path: /my_data_profile
  defaults: { _controller:AppBundle:Profile:myDataProfile }

modify_profile:
  path: /modify_profile
  defaults: { _controller:AppBundle:Profile:modifyData }

tournaments_json:
  path: /tournaments_json
  defaults: { _controller:AppBundle:Tournaments:getJsonTournaments }

