index:
  path: /
  defaults: { _controller:AppBundle:Main:index }

register:
  path: /register
  defaults: { _controller:AppBundle:Register:index }
  
home:
  path: /home
  defaults: { _controller:AppBundle:Home:index }

tournaments:
  path: /tournaments
  defaults: { _controller:AppBundle:Tournaments:index }

clash_royale:
  path: /tournaments/clash_royale
  defaults: { _controller:AppBundle:Tournaments:clash_royale }

active_account:
  path: /active_account/{username}
  defaults: { _controller:AppBundle:Register:active_account }

group:
  path: /group
  defaults: { _controller:AppBundle:Group:index }

groups_json:
  path: /group/groups_json/{filter_group}/{id_platform}
  defaults: { _controller:AppBundle:Group:get_groups }

close_group:
  path: /group/close_group/{id_group}
  defaults: { _controller:AppBundle:Group:close_group }

register_group:
  path: /group/register_group/{id_group}/{id_user}
  defaults: { _controller:AppBundle:Group:register_group }

signdown_group:
  path: /group/signdown_group/{id_group}
  defaults: { _controller:AppBundle:Group:signdown_group }

chat:
  path: /group/chat/{id_group}
  defaults: { _controller:AppBundle:Group:chat_group }

get_messages:
  path: /group/chat/get_messages
  defaults: { _controller:AppBundle:Group:get_messages }

add_message:
  path: /group/chat/{id_group}/add_message
  defaults: { _controller:AppBundle:Group:add_message }
