index:
  path: /
  defaults: { _controller:AppBundle:Main:index }

register:
  path: /register
  defaults: { _controller:AppBundle:Register:index }
  
home:
  path: /home
  defaults: { _controller:AppBundle:Home:index }

tournaments:
  path: /tournaments
  defaults: { _controller:AppBundle:Tournaments:index }

clash_royale:
  path: /tournaments/clash_royale
  defaults: { _controller:AppBundle:Tournaments:clash_royale }

active_account:
  path: /active_account/{username}
  defaults: { _controller:AppBundle:Register:active_account }

group:
  path: /group
  defaults: { _controller:AppBundle:Group:index }